# Generated by Django 4.1 on 2024-05-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intergration_app', '0002_userintergrationapp_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintergrationapp',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userintergrationapp',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
