# Generated by Django 4.1 on 2024-05-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intergration_app', '0005_remove_userintergrationapp_payment_payment_app_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userintergrationapp',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
