# Generated by Django 4.1 on 2024-05-25 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intergration_app', '0006_remove_userintergrationapp_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintergrationapp',
            name='Payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_app', to='intergration_app.payment'),
        ),
    ]
