# Generated by Django 4.1 on 2024-05-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intergration_app', '0007_userintergrationapp_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userintergrationapp',
            old_name='Payment',
            new_name='payment',
        ),
    ]
